name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  actions: read
  contents: write

env:
  BINARY_NAME: mdrs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: windows-x64
          - os: macos-latest
            target: darwin-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --release
          mkdir -p target/release/binaries/${{ matrix.target }}

      - name: Build and copy windows binaries
        if: ${{ matrix.target == 'windows-x64' }}
        run: |
          cp target/release/${{ env.BINARY_NAME }}.exe target/release/binaries/${{ matrix.target }}/

      - name: Build and copy linux/macos binaries
        if: ${{ matrix.target == 'linux-x64' || matrix.target == 'darwin-x64'}}
        run: |
          cp target/release/${{ env.BINARY_NAME }} target/release/binaries/${{ matrix.target }}/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.target }}
          path: target/release/binaries/${{ matrix.target }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore

      - name: Download binaries
        uses: dawidd6/action-download-artifact@v13
        with:
          path: builds/
          skip_unpack: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changes }}
          make_latest: true
          files: |
            builds/*
