name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  actions: read
  contents: write

env:
  BINARY_NAME: mdrs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: windows-x64
          - os: macos-latest
            target: darwin-x64
          - os: macos-latest
            target: darwin-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package binary (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist/${{ env.BINARY_NAME }}-${{ matrix.target }}
          cp target/release/${{ env.BINARY_NAME }} dist/${{ env.BINARY_NAME }}-${{ matrix.target }}/

          tar -czf ${{ env.BINARY_NAME }}-${{ matrix.target }}.tar.gz \
            -C dist \
            ${{ env.BINARY_NAME }}-${{ matrix.target }}

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir dist
          mkdir dist\${{ env.BINARY_NAME }}-${{ matrix.target }}

          copy target\release\${{ env.BINARY_NAME }}.exe `
            dist\${{ env.BINARY_NAME }}-${{ matrix.target }}\

          Compress-Archive `
            -Path dist\${{ env.BINARY_NAME }}-${{ matrix.target }} `
            -DestinationPath ${{ env.BINARY_NAME }}-${{ matrix.target }}.zip

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.target }}
          path: |
            ${{ env.BINARY_NAME }}-${{ matrix.target }}.*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore

      - name: Download archives
        uses: actions/download-artifact@v4
        with:
          path: builds/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changes }}
          make_latest: true
          files: |
            builds/**/*.tar.gz
            builds/**/*.zip
